server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

zuul:
  #ignored-services: microservicecloud-dept #原真实服务名忽略 (单个具体，多个可以用"*")
  prefix: /collabtech
  ignored-services: "*"
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**

#before http://myzuul.com:9527/microservicecloud-dept/dept/get/2
#after http://myzuul.com:9527/mydept/dept/get/1

#最终 http://myzuul.com:9527/collabtech/mydept/dept/get/1

info:
  app.name: collabtech-microcloud
  company.name: www.collabtech.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$

