###########################
###      生产环境       ###
###########################
#contextpath & port
server:
  servlet:
    context-path: /
  port: 9999

# mysql

#druid数据源配置
spring:
  datasource:
    url: jdbc:mysql://172.16.5.101:3306/integral_pay?allowMultiQueries=true&useSSL=false
    username: root
    password: Ibudata@123
    driver-class-name: com.mysql.jdbc.Driver

#mybatis settings
mybatis:
  mapper-locations: classpath:mapper/*.xml
